config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  devise_for :users
  root to: "costumes#index"
  get "dashboard", to: "pages#dashboard"
  get "mycostumes", to: "pages#mycostumes"

  get "profile", to: "pages#profile"

  resources :costumes do
    resources :bookmarks, only: [:create]
    resources :bookings, only: [:new, :create]
  end

  resources :bookmarks, only: :destroy

  resources :bookings, only: [:update, :destroy] do
    resources :reviews, only: [:new, :create]
    member do
      post :accept
      post :close
    end
  end

end

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

# Defines the root path route ("/")
# root "articles#index"

app/models/costume.rb
class Costume < ApplicationRecord
  include CostumeConcern
  
  belongs_to :user
  has_many :bookings, dependent: :destroy

  has_many_attached :images
  has_many :reviews, dependent: :destroy, through: :bookings
  has_many :bookmarks, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :name, presence: true, length: { minimum: 2 }
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :description, length: { minimum: 6 }

  include PgSearch::Model
  pg_search_scope :search_by_name_and_description,
    against: %i[name description],
    using: {
      tsearch: { prefix: true }
    }

end

app/controllers/costumes_controller.rb
class CostumesController < ApplicationController
  before_action :set_costume, only: %i[show destroy edit update]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @costumes = policy_scope(Costume)
    authorize @costumes
    if params[:query]
      @costumes = Costume.search_by_name_and_description("#{params[:query]}")
      # @costumes = @costumes.reject { |costume| costume.user == current_user }
    else
      @costumes = Costume.all
    end

    @costumes = Costume.all if @costumes.empty?
  end

  def show
    authorize @costume
    @costumes = []
    @costumes << @costume
    @markers = [
      {
        lat: @costume.geocode[0],
        lng: @costume.geocode[1],
        marker_html: render_to_string(partial: "marker")
      }
    ]
  end

  def new
    @costume = Costume.new
    authorize @costume
    @costume.user = current_user
  end

  def create
    @costume = Costume.new(costume_params)
    @costume.user = current_user
    @costume.address = @costume.user.address
    authorize @costume
    # attacher une image ? se fait dans les params
    if @costume.save
      redirect_to costumes_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @costume
    @costume.destroy
    redirect_to costumes_url, notice: "costume was successfully destroyed."
  end

  def edit
    authorize @costume
  end

  def update
    authorize @costume
    if @costume.update(costume_params)
      redirect_to @costume, notice: "costume was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_costume
    @costume = Costume.find(params[:id])
  end

  def costume_params
    params.require(:costume).permit(:name, :price, :description, :address, images: [], query:)
  end
end

app/views/costumes/_form.html.erb
<%= simple_form_for (@costume) do |f| %>
  <%= f.input :name %>
  <%= f.input :price %>
  <%= f.input :description %>
  <%= f.input :images, as: :file, input_html: { multiple: true } %>
  <%= f.submit "Create new costume", class: "btn-primary" %>

<% end %>

app/views/costumes/_marker.html.erb
<%= image_tag "logo.png", height: 30, width: 30, alt: "Logo" %>

app/views/costumes/_reviewform.erb
<%= simple_form_for [@booking] do |f|%>
  <%= f.input :costume_rating %>
  <%= f.input :costume_review %>
  <%= f.input :image, as: :file %>
  <%= f.submit "Submit my review", class: "btn btn-flat" %>
<% end %>

app/views/costumes/edit.html.erb
<div class="container mt-4">

  <%= simple_form_for (@costume), html: { multipart: true } do |f| %>
    <%= f.input :name %>
    <%= f.input :price %>
    <%= f.input :description %>
    <%= f.input :image, as: :file %>
    <%= f.submit "Update Costume", class: "btn btn-danger" %>
  <% end %>

  <%= link_to "retour à la liste", costumes_path %>

</div>

app/views/costumes/index.html.erb
<div class="banner mb-3 d-flex align-items-center">
  <div class="container">
      <h1>Costumizer</h1>
      <h2>Be whoever you want, whenever you want</h2>
  </div>
</div>


<div class="container mt-5">
  <div class="cards">
    <% @costumes.each do |costume| %>
      <% if costume.user != current_user %>
        <div class="wrapper-card-trip-index">
          <div class="fav-button">
            <% if current_user %>
              <% unless Bookmark.where({user: current_user, costume: costume}).any? %>
                <%= link_to costume_bookmarks_path(costume),data: {turbo_method: :post}, class:"text-decoration-none btn-flat" do %>
                  <i class="fa-regular fa-heart"></i>
                <% end %>
              <% else %>
                <%= link_to bookmark_path(Bookmark.where({user: current_user, costume: costume}).first),data: {turbo_method: :delete}, class:"text-decoration-none btn-flat" do %>
                  <i class="fas fa-heart"></i>
                <% end %>
              <% end %>
            <% end %>
          </div>
          <%= link_to costume_path(costume), class:"text-decoration-none" do %>

            <div class="card-trip-index">

              <% if costume.images.attached? %>
                <%= cl_image_tag costume.images.first.key, crop: :fill %>
              <% end %>

              <div class="card-trip-infos-index">
                <div>
                  <h2> <%= "#{costume.name}" %></h2>
                </div>
                <h2 class="card-trip-pricing-index"> <%= "#{costume.price}€" %> </h2>
              </div>

            </div>

          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>

  <% if current_user %>
  <div class="container">
    <div class="row">
      <div class="col-8">
        <h3 class="rubrik">My Costumes</h3>
      </div>
    </div>
  </div>
    <div class="cards">
    <% @costumes.each do |costume| %>
      <% if costume.user == current_user %>
        <%= link_to costume_path(costume), class:"text-decoration-none" do%>
          <div class="wrapper-card-trip-index">
            <div class="card-trip-index">
              <% if costume.images.attached? %>
                <%= cl_image_tag costume.images.first.key, crop: :fill  %>
              <% end %>
              <div class="card-trip-infos-index">
                <div>
                  <h2> <%= "#{costume.name}" %></h2>
                </div>
                  <h2 class="card-trip-pricing-index"> <%= "#{costume.price}€" %> </h2>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
    </div>
  <% end %>
</div>

app/views/costumes/new.html.erb
<div class="container mt-4">
  <div class="page-content">
    <%= render 'costumes/form' %>
  </div>
  <div class="mt-4">
    <%= link_to "Back to dashboard", dashboard_path %>
  </div>

</div>

app/views/costumes/show.html.erb
<div class="page-content">

<div class="container mt-4">

  <div class="d-flex mb-4 mt-4 justify-content-between">
    <%# image %>
    <div class="m-4">
      <% if @costume.images.attached? %>

        <% @costume.images.each do |image| %>
            <div class="img-fav">
              <%= cl_image_tag image.key, height: 400, width: 400, crop: :fill %>
                <%# Adding favorite button %>
              <div class="fav-button">
                <% if current_user %>
                  <% unless Bookmark.where({user: current_user, costume: @costume}).any? %>
                    <%= link_to costume_bookmarks_path(@costume),data: {turbo_method: :post}, class:"text-decoration-none btn-flat" do %>
                      <i class="fa-regular fa-heart"></i>
                    <% end %>
                  <% else %>
                    <%= link_to bookmark_path(Bookmark.where({user: current_user, costume: @costume}).first),data: {turbo_method: :delete}, class:"text-decoration-none btn-flat" do %>
                      <i class="fas fa-heart"></i>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
              <%# End of adding favorite button %>
            </div>
        <% end %>
      <% end %>
    </div>
    <%# info %>
    <div class="m-4">
      <h2><%= "#{@costume.name}" %></h2>
      <h3><%= "#{@costume.price}" %>€ / day</h2>
      <% unless @costume.bookings.empty? %>
        <% @note ||= 0 %>
          <% @costume.bookings.each do |booking|%>
          <% @note += booking.review.rating %>
          <% end %>
        <% @average_note = @note / @costume.bookings.length %>
        <% @average_note.times do  %>
          <i class='fa-solid fa-star active'></i>
        <% end %>
        <% (5 - @average_note).times do  %>
          <i class='fa-solid fa-star active opacity-25'></i>
        <% end %>
      <% end %>

      <p>This wonderful costume is offered by <%= "#{@costume.user.user_name}" %> !</p>
      <%= link_to "Book this costume", new_costume_booking_path(@costume), class: "btn-classic"%>
      <% if current_user %>
        <% unless Bookmark.where({user: current_user, costume: @costume}).any? %>
          <%= link_to costume_bookmarks_path(@costume),data: {turbo_method: :post}, class:"text-decoration-none btn-classic" do %>
            <i class="fas fa-heart"></i> Add to favorite
          <% end %>
        <% else %>
          <%= link_to bookmark_path(Bookmark.where({user: current_user, costume: @costume}).first),data: {turbo_method: :delete}, class:"text-decoration-none btn-flat" do %>
            <i class="fas fa-heart"></i> Remove from favorite
          <% end %>
        <% end %>
      <% end %>
    </div>
    <%# calendrier %>
    <div class="m-4">
      <%= simple_form_for [@costume, Booking.new], html: { data: { controller: 'flatpickr', flatpickr_dates_value: @costume.flatpickr_booked_dates_object, flatpickr_price_value: @costume.price }  } do |f| %>
        <%= f.input :start_date,
                    label: false,
                    as: :string,
                    input_html: {
                      class: 'd-none',
                      data: {
                        flatpickr_target: 'startDateInput',
                        dynamic_booking_price_target: 'startDateInput',
                        action: 'change->flatpickr#updatePrice'
                      }
                    } %>
        <%= f.input :end_date,
                    label: false,
                    as: :string,
                    input_html: {
                      class: 'd-none',
                      data: {
                        flatpickr_target: 'endDateInput',
                        dynamic_booking_price_target: 'endDateInput',
                        action: 'change->flatpickr#updatePrice'
                      }
                    } %>
        <div class="d-flex justify-content-around align-items-center">
          <div>
            <%= f.submit 'Book now!', class: 'btn btn-primary' %>
          </div>
          <div>
            Total price: <span data-flatpickr-target="priceHolder"><%= @costume.price%></span> €
          </div>
        </div>
      <% end %>
    </div>
  </div>

    <p style="text-align: justify"><%= "#{@costume.description}" %></p>

      <% if current_user == @costume.user %>
        <%= link_to "Edit", edit_costume_path(@costume), class: "btn-classic"%>
        <%= link_to "Delete",
            costume_path(@costume),
            class: "btn-classic",
            data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
          %>
      <% end %>

    <div class="map-comment-grid">
      <div>
        <h2 class="mt-4">Reviews</h2>
          <% @costume.bookings.each do |booking| %>
            <%if booking.review%>
              <div class="review-card">
                <p class="pt-3">Posted by <%= booking.user.user_name %> <p>
                <% (1..booking.review.rating).to_a.each do |star| %>
                  <i class="fa-solid fa-star active"></i>
                <% end %>
                <p class="mt-3 pb-3"><%= booking.review.content %></p>
              </div>
            <% end %>
            <% (5 - (1..booking.review.rating).to_a.length).times do %>
              <i class="fa-solid fa-star active opacity-25"></i>
            <% end %>
            <p class="mt-3 pb-3"><%= booking.review.content %></p>
          </div>
        <% end %>
      </ul>
    </div>

        <div>
          <h2 class="mt-4">Costume's location</h2>
          <div style="width: 100%; height: 300px;"
            data-controller="map"
            data-map-markers-value="<%= @markers.to_json %>"
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>
      </div>
    </div>

  </div>


</div>

</div>