config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  devise_for :users
  root to: "costumes#index"
  get "dashboard", to: "pages#dashboard"
  get "mycostumes", to: "pages#mycostumes"

  get "profile", to: "pages#profile"

  resources :costumes do
    resources :bookmarks, only: [:create]
    resources :bookings, only: [:new, :create]
  end

  resources :bookmarks, only: :destroy

  resources :bookings, only: [:update, :destroy] do
    resources :reviews, only: [:new, :create]
    member do
      post :accept
      post :close
    end
  end

end

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

# Defines the root path route ("/")
# root "articles#index"

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :costume
  has_one :review

  validates :start_date, :end_date, presence: true # , if: :correct_date?
  validates :status, presence: true

  def correct_date?
    errors.add :end_date, "must be after start date" if end_date <= start_date
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
    authorize @bookings
    # mes demandes de reservation auprès d'autres loueurs
  end

  def show
    set_booking
    authorize @booking
  end

  def new
    @costume = Costume.find(params[:costume_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    authorize @booking
    @costume = Costume.find(params[:costume_id])
    @booking.costume = @costume
    @booking.user = current_user
    @booking.status = "pending"
    if @booking.save
      redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    set_booking
    authorize @booking
  end

  def update
    set_booking
    authorize @booking
    @booking.update(booking_params)
    redirect_to user_booking_path(@booking)
  end

  def destroy
    set_booking
    authorize @booking
    @booking.destroy
    redirect_to user_bookings_path
  end

  def accept
    set_booking
    authorize @booking
    @booking.status = "confirmed"
    @booking.save
    redirect_to dashboard_path
  end

  def close
    set_booking
    authorize @booking
    @booking.status = "closed"
    @booking.save
    redirect_to new_booking_review_path(@booking)
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :user_id, :costume_id, :client_review, :client_rating, :costume_review, :client_rating, :status)
  end


end

app/views/bookings/index.html.erb
<h1> Bienvenue sur la page d'index des réservations</h1>

<div class="container">
  <div class="row d-flex justify-content-between">

    <%# IF RENTER%>
    <%# PENDING RESA%>
    <% @bookings.each do |booking| %>
       <%# if booking.available? %>
        <%= link_to booking_path(booking), class:"text-decoration-none" do%>
          <div class="card-trip col-4 p-1">
            <%# image à mettre %>
            <div class="card-trip-infos">
              <div>
                <h2> <%= "#{booking.user_id} have made a reservation from #{booking.start_date} to #{booking.end_date}" %></h2>
                <%# ajouter un bouton accept / decline %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
      <%# ACCEPTED RESA%>
      <%# ELSE CLIENT%>

  </div>
</div>

app/views/bookings/new.html.erb
<h1>Bienvenue sur la page de booking d'un costume</h1>

<%# ==================flatpickr disable dates======================= %>
  <div class="row">
    <div class="col">
        <%= simple_form_for [@costume, @booking], html: { data: { controller: 'flatpickr', flatpickr_dates_value: @costume.flatpickr_booked_dates_object }  } do |f| %>
          <%= f.input :start_date,
                      # label: false,
                      as: :string,
                      input_html: {
                          data: {
                          flatpickr_target: 'startDateInput',

                        }
                      } %>
          <%= f.input :end_date,
                      # label: false,
                      as: :string,
                      input_html: {
                        class: 'd-none',
                        data: {
                          flatpickr_target: 'endDateInput'
                        }
                      } %>
          <%= f.submit 'Book now!', class: 'btn btn-primary' %>
        <% end %>
    </div>
  </div>