config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  devise_for :users
  root to: "costumes#index"
  get "dashboard", to: "pages#dashboard"
  get "mycostumes", to: "pages#mycostumes"

  get "profile", to: "pages#profile"

  resources :costumes do
    resources :bookmarks, only: [:create]
    resources :bookings, only: [:new, :create]
  end

  resources :bookmarks, only: :destroy

  resources :bookings, only: [:update, :destroy] do
    resources :reviews, only: [:new, :create]
    member do
      post :accept
      post :close
    end
  end

end

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

# Defines the root path route ("/")
# root "articles#index"

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This website is made with <i class="fas fa-heart"></i> at Costumizer
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon bg-img fixed-top"
  data-controller="navbar" data-action="scroll@window->navbar#updateNavbar">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="search-form-control">
      <%= form_with url: costumes_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a Costume..."
      %>

        <button name="button" type="submit" class="btn btn-ghost ">
          <i class="fas fa-search"></i>
        </button>

      <% end %>
    </div>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto d-flex align-items-center" >
        <li>
          <% if user_signed_in? %>
            <%= link_to "My dashboard", dashboard_path, class: "btn-nav"%>
        </li>
        <li>
          <%= link_to "Add a new costume", new_costume_path, class: "btn-nav"%>
        </li>
            <li class="nav-item ms-2 dropdown">
              <% if current_user.avatar.key? %>
              <%= cl_image_tag current_user.avatar.key, :width=>100, :height=>100, :gravity=>"face", :radius=>"max", :crop=>"fill", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% end %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Edit my profile", "#", class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
            </li>
            <% else %>
            <li class="" id="login">
            <%= link_to "Login", new_user_session_path, class: "btn-nav" %>
          </li>
          <% end %>
      </ul>
    </div>
  </div>
</div>

<%#
<div class="dropdown">
  <input type="checkbox" id="dropdown">

  <label class="dropdown__face" for="dropdown">
    <div class="dropdown__text">Dropdown</div>

    <div class="dropdown__arrow"></div>
  </label>

  <ul class="dropdown__items">
    <li>🙂</li>
    <li>😺</li>
    <li>😽</li>
    <li>😎</li>
    <li>🤗</li>
  </ul>
</div>

<svg>
  <filter id="goo">
    <feGaussianBlur in="SourceGraphic" stdDeviation="10" result="blur" />
    <feColorMatrix in="blur" type="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -7" result="goo" />
    <feBlend in="SourceGraphic" in2="goo" />
  </filter>
</svg> %>